alias sinstall='sudo apt install -yf'
alias atom='snap run atom'
alias c='clear && . ~/.bashrc'
alias repo='sudo add-apt-repository -y'
alias alien='~/.bash_aliases'
alias supdate='sudo apt update'
alias uninstall='sudo apt remove --purge'
alias fsupdate='sudo apt update && sudo apt upgrade -y && sudo apt full-upgrade -y && sudo apt autoremove -y'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias startplex='sudo systemctl start plexmediaserver'
alias get-users='cut -d: -f1 /etc/passwd'

