#!/bin/bash

# Create Bash Functions & Alias file
touch ~/.bash_func
touch ~/.bash_aliases
echo -e "if [ -f ~/.bash_func ]; then
	. ~/.bash_func
fi

export PATH=\$PATH:/snap/bin" >> ~/.bashrc

# Functions for creating aliases and functions
echo -e "
mkalien(){
	if [ \$# -eq 0 ]; then
		read -p 'Name: ' name;
		read -p 'Alias: ' alien;
		echo -e \"alias \${name}=\"\${alien}\"\" >> ~/.bash_aliases;
		. ~/.bash_aliases
	else
		echo -e \"alias \$1=\"\$2\"\" >> ~/.bash_aliases;
		. ~/.bash_aliases
	fi
}

mkfunc(){
	read -p 'Name: ' name;
	read -p 'Function: ' funk;
	echo -e \"\${name}(){\\\n\\\t\${funk}\\\n}\" >> ~/.bash_func;
	. ~/.bash_func
}" >> ~/.bash_func

# Full System Update
sudo apt update; sudo apt upgrade -y; sudo apt full-upgrade -y; sudo apt autoremove -y

# Installs
sudo apt update;
sudo apt install -yf snapd git open-vm-tools-desktop build-essential python-pip python-dev python-setuptools python-wheel python3-pip python3-dev python3-setuptools python3-wheel virtualenv;
sudo snap install code --classic;
sudo snap install atom --classic;
. ~/.bashrc;

# Customize Linux Theme and Background
gsettings set org.cinnamon.theme name "Mint-Y-Dark-Orange";
gsettings set org.cinnamon.desktop.interface gtk-theme "Mint-Y-Dark-Orange";
gsettings set org.cinnamon.desktop.wm.preferences theme "Mint-Y-Dark-Orange";
curl 'https://i.imgur.com/77ofjEU.jpg' --output ~/Pictures/wallpaper.jpg;
gsettings set org.cinnamon.desktop.background picture-uri  "file:~/Pictures/wallpaper.jpg";

# Configure Python
pip3 install pep8 autopep8

# Configure Atom
apm install script intentions busy-signal linter-ui-default linter python-autopep8
